# .github/workflows/pack-release.yml

name: Pack and Release Resource Pack

# 触发条件
on:
  push:
    branches:
      - main
    paths:
      - "assets/**"
      - ".github/workflows/**"

jobs:
  build-and-release:
    # 使用最新的 Ubuntu 系统作为运行环境
    runs-on: ubuntu-latest

    # 声明此任务需要的权限
    permissions:
      contents: write # <-- 这是解决问题的关键！授予创建 Release 的写入权限

    steps:
      # 第一步：检出仓库代码
      - name: Checkout repository
        uses: actions/checkout@v4

      # 第二步：为 Minecraft 1.20.1 打包
      # pack_format: 15 对应 1.20 ~ 1.20.1
      - name: Zip for Minecraft 1.20.1
        run: |
          echo '{"pack":{"pack_format":15,"description":"Harvestpack Modern for Pam'\''s HC2"}}' > pack.mcmeta
          zip_name="Harvestpack-Modern-1.20.1.zip"
          zip -r ${{ github.workspace }}/${zip_name} assets pack.mcmeta pack.png

      # 第三步：为 Minecraft 1.21.1 打包
      # pack_format: 48 对应 1.21.1+
      - name: Zip for Minecraft 1.21.1
        run: |
          echo '{"pack":{"pack_format":48,"description":"Harvestpack Modern for Pam'\''s HC2"}}' > pack.mcmeta
          zip_name="Harvestpack-Modern-1.21.1.zip"
          zip -r ${{ github.workspace }}/${zip_name} assets pack.mcmeta pack.png

      # 第四步：创建 Release 并上传打包好的文件
      - name: Create Release and Upload Assets
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: "${{ github.workspace }}/Harvestpack-Modern-*.zip"
          tag: release-${{ github.sha }}
          name: "Auto Release ${{ github.run_number }} (${{ github.sha }})"
          allowUpdates: true
          prerelease: true
